### ISSUE TITLE
Need to add development branch

### ISSUE THREAD

**Issue by samuelhward** [Woodruff-Scientific-Ltd/PyFECONS#51]
- main should be reserved for tested, stable, production releases
- development should be centered on "dev" branch, where any potential issues are finally identified, collected, and solved

**Comment by craastad** [comment]
Thanks for creating an issue with suggestion.

I don't think our project is in a state where we need a dev branch yet, it's been basically one developer (me) until now. The releases are still labeled as pre-release and created after every merge to main. Creating PRs for review are enough at this point, without the complexity of creating extra PRs to merge dev to main.

In my experience, I've very rarely used a development branch for backend code, since all testing can be done in code and it adds complexity of syncing. Dev branches are useful for frontend and especially mobile apps, or if the project scale grows enough where we need a dev branch.

I would suggest working towards writing automated tests that are run on each push to a branch and need to pass before merging a branch into main. We have just a few tests for one little part of functionality, but could really use some integration tests that are ran automatically (maybe make an issue for those?).

**Comment by samuelhward** [comment]
Sure thing, opened originally because scaling either requires more tests or more stringent review/merging processes. More tests better though!
